name: efficient
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.14.4
  - pip=26.0.1
  - setuptools=82.0.1
  - numpy=2.4.4
  - scipy=1.17.1
  - pandas=3.0.2
  - polars=1.39.0
  - scikit-learn=1.8.0
  - statsmodels=0.14.6
  - numexpr=2.14.1
  - patsy=1.0.2
  - dask=2026.3.0
  - joblib=1.5.3
  - mpi4py=4.0.3
  - mpich=4.3.2
  - h5py=3.16.0
  - pytables=3.11.1
  - pyarrow=23.0.1
  - nibabel=5.4.2
  - fsspec=2026.4.0
  - hdf5=2.0.0
  - black=26.3.1
  - ruff=0.15.1
  - flake8=7.3.0
  - autopep8=2.0.4
  - pylint=4.0.5
  - isort=8.0.1
  - yapf=0.43.0
  - pydocstyle=6.3.0
  - python-lsp-server=1.14.0
  - python-lsp-black=2.0.0
  - python-lsp-ruff=2.3.0
  - python-lsp-jsonrpc=1.1.2
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - requests=2.33.1
  - aiohttp=3.13.5
  - asyncssh=2.21.1
  - beautifulsoup4=4.14.3
  - cryptography=46.0.7
  - pyyaml=6.0.3
  - click=8.2.1
  - jinja2=3.1.6
  - rich=14.2.0
  - arrow=1.4.0
  - cookiecutter=2.7.1
  - pygithub=2.9.1
  - python-slugify=8.0.4
  - dill=0.4.0
  - cloudpickle=3.1.2
  - toolz=1.1.0
  - lmdb=0.9.31
  - sphinx=9.1.0

  # R-related packages
  - r-base=4.6.0
  - r-pracma
  - r-this.path
  - r-oro.nifti
  - r-RNifti
  - r-biocmanager
  - r-data.table
  - r-arrow
  - bioconductor-rhdf5
  - bioconductor-delayedmatrixstats
  - bioconductor-hdf5array
  - bioconductor-delayedarray