name: efficient
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - numpy=2.4.4
  - pandas=3.0.2
  - polars=1.39.0
  - scikit-learn=1.8.0
  - statsmodels=0.14.6
  - numexpr=2.14.1
  - patsy=1.0.2
  - dask=2026.3.0
  - joblib=1.5.3
  - h5py=3.16.0
  - nibabel=5.4.2
  - fsspec=2026.4.0
  - pyarrow=23.0.1
  - dill=0.4.0
  - cloudpickle=3.1.2
  - toolz=1.1.0

  # R-related packages
  - r-base=4.5.0
  - r-pracma
  - r-this.path
  - r-oro.nifti
  - r-rnifti
  - r-biocmanager
  - r-data.table
  - r-arrow
  - bioconductor-rhdf5
  - bioconductor-delayedmatrixstats
  - bioconductor-hdf5array
  - bioconductor-delayedarray