name: efficient
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.14.4
  - numpy=2.4.4
  - pandas=3.0.2
  - polars=1.39.0
  - scikit-learn=1.8.0
  - statsmodels=0.14.6
  - numexpr=2.14.1
  - patsy=1.0.2
  - dask=2026.3.0
  - joblib=1.5.3
  - h5py=3.16.0
  - nibabel=5.4.2
  - fsspec=2026.4.0
  - pyarrow=23.0.1
  - dill=0.4.0
  - cloudpickle=3.1.2
  - toolz=1.1.0

  # R-related packages
  - r-base=4.5.0
  - r-pracma=2.4.6
  - r-this.path=2.8.0
  - r-oro.nifti=0.11.4
  - r-rnifti=1.9.0
  - r-biocmanager=1.30.27
  - r-data.table=1.18.4
  - r-arrow=24.0.0
  - bioconductor-rhdf5=2.56.0
  - bioconductor-delayedmatrixstats=1.34.0
  - bioconductor-hdf5array=1.40.0
  - bioconductor-delayedarray=0.38.1